### ISSUE TITLE
Hi i have a problem 301

### ISSUE THREAD

**Issue by geforcefx** [staude/disable-author-pages#5]
My complett site is 301 www.gross-electronic.de/games_blog

beforce i have 200 and this is right

can you help me i have deinstall the plugin not better

HTTP/1.1 301 Moved Permanently
Date: Fri, 02 Dec 2016 10:27:32 GMT
Server: Apache
Location: http://www.gross-electronic.de/games_blog/
Vary: Accept-Encoding
Content-Type: text/html; charset=iso-8859-1
Content-Length: 250
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.gross-electronic.de/games_blog/">here</a>.</p>
</body></html>

**Comment by staude** [comment]
Wie schon in der Mail geschrieben:

Kann ich so nicht reproduzieren und das Plugins schriebt auch keine .haccess Einträge oder ähnliches.
